// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AnimateList: typeof import('./src/components/AnimateList.vue')['default']
    ARow: typeof import('ant-design-vue/es')['Row']
    Aside: typeof import('./src/components/layout/aside.vue')['default']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    Children: typeof import('./src/components/children.vue')['default']
    copy: typeof import('./src/components/layout/index copy.vue')['default']
    Index2: typeof import('./src/components/layout/index2.vue')['default']
    Index3: typeof import('./src/components/layout/index3.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Menus: typeof import('./src/components/layout/menus.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    Parent: typeof import('./src/components/parent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tags: typeof import('./src/components/layout/tags.vue')['default']
    TypeTest: typeof import('./src/components/TypeTest.vue')['default']
  }
}
