// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        404: typeof import('./src/components/404.vue')['default'];
        AButton: typeof import('ant-design-vue/es')['Button'];
        ACard: typeof import('ant-design-vue/es')['Card'];
        ACol: typeof import('ant-design-vue/es')['Col'];
        notification: typeof import('ant-design-vue/es')['notification'];
        AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider'];
        ADrawer: typeof import('ant-design-vue/es')['Drawer'];
        ADropdown: typeof import('ant-design-vue/es')['Dropdown'];
        AForm: typeof import('ant-design-vue/es')['Form'];
        AFormItem: typeof import('ant-design-vue/es')['FormItem'];
        AInput: typeof import('ant-design-vue/es')['Input'];
        AInputPassword: typeof import('ant-design-vue/es')['InputPassword'];
        ALayout: typeof import('ant-design-vue/es')['Layout'];
        ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
        ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
        ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider'];
        AMenu: typeof import('ant-design-vue/es')['Menu'];
        AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider'];
        AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
        AnimateList: typeof import('./src/components/AnimateList.vue')['default'];
        ARow: typeof import('ant-design-vue/es')['Row'];
        ASelect: typeof import('ant-design-vue/es')['Select'];
        ASelectOption: typeof import('ant-design-vue/es')['SelectOption'];
        ASpin: typeof import('ant-design-vue/es')['Spin'];
        ASubMenu: typeof import('ant-design-vue/es')['SubMenu'];
        Amodal: typeof import('ant-design-vue/es')['Modal'];
        ASwitch: typeof import('ant-design-vue/es')['Switch'];
        ATable: typeof import('ant-design-vue/es')['Table'];
        Children: typeof import('./src/components/children.vue')['default'];
        FullScreen: typeof import('./src/components/FullScreen.vue')['default'];
        Layout: typeof import('./src/components/layout/index.vue')['default'];
        Loading: typeof import('./src/components/Loading/index.vue')['default'];
        Lottie: typeof import('./src/components/lottie/index.vue')['default'];
        NotFound: typeof import('./src/components/NotFound.vue')['default'];
        Parent: typeof import('./src/components/parent.vue')['default'];
        PicCode: typeof import('./src/components/PicCode/index.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        Settings: typeof import('./src/components/layout/settings.vue')['default'];
        Tags: typeof import('./src/components/layout/tags.vue')['default'];
        TypeTest: typeof import('./src/components/TypeTest.tsx')['default'];
    }
}
