// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./components/404.vue')['default']
    AnimateList: typeof import('./components/AnimateList.vue')['default']
    Children: typeof import('./components/children.vue')['default']
    FullScreen: typeof import('./components/FullScreen.vue')['default']
    Layout: typeof import('./components/layout/index.vue')['default']
    Loading: typeof import('./components/Loading/index.vue')['default']
    Lottie: typeof import('./components/lottie/index.vue')['default']
    NotFound: typeof import('./components/NotFound.vue')['default']
    Parent: typeof import('./components/parent.vue')['default']
    PicCode: typeof import('./components/PicCode/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/layout/settings.vue')['default']
    Tags: typeof import('./components/layout/tags.vue')['default']
    TypeTest: typeof import('./components/TypeTest.vue')['default']
  }
}
